---
commitizen:
  name: cz_conventional_commits
  tag_format: v$major.$minor.$patch$prerelease
  version: 2.2.0
  version_files:
  - api/internal/config.go:^    Version =
  - 'charts/autoversioned/Chart.yaml:^version:'
  - 'charts/autoversioned/Chart.yaml:^appVersion:'
