environments:
  default:
    values:
      - ./deployment/values-local.yaml
  dev:
    values:
      - ./deployment/values-dev.yaml
  staging:
    values:
      - ./deployment/values-staging.yaml
  prod:
    values:
      - ./deployment/values-prod.yaml
---
releases:
  - name: autoversioned
    chart: ./charts/autoversioned
    kubeContext: nonExistingContextToAvoidDeployingToProdByMistake
    values:
      - {{ .Values | expandSecretRefs | toYaml | nindent 8 }}
