# https://skaffold.dev/docs/references/yaml
apiVersion: skaffold/v4beta2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: true
    useDockerCLI: true
  artifacts:
    - image: mtrqq/autoversioned
      context: api
      docker:
        cacheFrom:
          - golang:1.20-alpine
          - alpine:3.17.2

deploy:
  helm:
    releases:
      - name: autoversioned
        chartPath: charts/autoversioned
        valuesFiles:
        - charts/autoversioned/values.yaml
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_mtrqq_autoversioned}}"
          image.tag: "{{.IMAGE_TAG_mtrqq_autoversioned}}@{{.IMAGE_DIGEST_mtrqq_autoversioned}}"
        setValues:
          image.pullPolicy: "IfNotPresent"
