{{- if .Values.secretValue -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "autoversioned.fullname" . }}
  annotations:
    kubernetes.io/service-account.name: {{ template "autoversioned.serviceAccountName" . }}
data:
  secretValue: {{ .Values.secretValue | b64enc }}
{{- end -}}
