name: "lint-pr"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title

      - uses: marocchino/sticky-pull-request-comment@v2
        # When the previous steps fails, the workflow would stop. By adding this
        # condition you can continue the execution with the populated error message.
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Pull request titles require to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      # Delete a previous comment when the issue has been resolved
      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
